//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday_details
    {
        public int hd_id { get; set; }
        public string hd_name { get; set; }
        public System.DateTime hd_from { get; set; }
        public System.DateTime hd_to { get; set; }
        public int hy_id { get; set; }
        public int generated_by { get; set; }
    
        public virtual user user { get; set; }
        public virtual holiday_year holiday_year { get; set; }
    }
}
