//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mmpEntities : DbContext
    {
        public mmpEntities()
            : base("name=mmpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<category_type_details> category_type_details { get; set; }
        public virtual DbSet<holiday_details> holiday_details { get; set; }
        public virtual DbSet<holiday_year> holiday_year { get; set; }
        public virtual DbSet<leave_details> leave_details { get; set; }
        public virtual DbSet<project_details> project_details { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sector> sectors { get; set; }
        public virtual DbSet<timesheet_day_details> timesheet_day_details { get; set; }
        public virtual DbSet<timesheet_details> timesheet_details { get; set; }
        public virtual DbSet<timesheet_mr> timesheet_mr { get; set; }
        public virtual DbSet<timesheet> timesheets { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
