//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presence
    {
        public int p_id { get; set; }
        public System.DateTime p_date { get; set; }
        public Nullable<double> total_hours { get; set; }
        public string leave_status { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
