//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesheet_details()
        {
            this.timesheet_day_details = new HashSet<timesheet_day_details>();
        }
    
        public int tsd_id { get; set; }
        public int tsd_timesheet_id { get; set; }
        public int tsd_category_id { get; set; }
        public int tsd_category_type_id { get; set; }
        public string timesheet_entry_type { get; set; }
    
        public virtual category category { get; set; }
        public virtual category_type_details category_type_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheet_day_details> timesheet_day_details { get; set; }
        public virtual timesheet timesheet { get; set; }
    }
}
