//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public timesheet()
        {
            this.timesheet_details = new HashSet<timesheet_details>();
        }
    
        public int timesheet_id { get; set; }
        public int timesheet_user { get; set; }
        public Nullable<System.DateTime> time_my { get; set; }
        public Nullable<int> updated_by { get; set; }
        public string timesheet_status { get; set; }
        public Nullable<System.DateTime> timesheet_status_update { get; set; }
        public int timesheet_caller { get; set; }
        public Nullable<System.DateTime> tsmr_extension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timesheet_details> timesheet_details { get; set; }
        public virtual timesheet_mr timesheet_mr { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
