//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timesheet_day_details
    {
        public int tdd_id { get; set; }
        public System.DateTime tdd_day { get; set; }
        public Nullable<double> workhours { get; set; }
        public Nullable<int> tsd_id { get; set; }
    
        public virtual timesheet_details timesheet_details { get; set; }
    }
}
